version: "3.8"
services:
  mongodb:
    image: 210847201921.dkr.ecr.us-west-2.amazonaws.com/mongo
    container_name: surfscribe-mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
    restart: always
    ports:
      - 27017:27017
    volumes:
      - data:/data
  mongo-express:
    image: 210847201921.dkr.ecr.us-west-2.amazonaws.com/mongo-express
    container_name: surfscribe-mongo-express
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
      - ME_CONFIG_MONGODB_SERVER=mongodb
    restart: always
    ports:
      - 8081:8081
  surfscribe-backend:
    build: .
    container_name: surfscribe-backend
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
volumes:
  data: {}

networks:
  default:
    name: mongodb_network
